/**
 * @description       : This class extends the inerface so we can use in another class.                                          
 * @author            : prashant.kumbhar@skinternational.com
 * @last modified on  : 10-11-2023
 * @last modified by  :  prashant.kumbhar@skinternational.com
**/

public virtual class IPriceBookServiceImp implements IPriceBookService {
    
/** 
* @Description - This method is Used Call Different Classes based on PriceList Data. 
* @param List :priceList,String-Ontrigger.
* @return  -    void
*/           
    public virtual void createPriceBookAndEntries(List<Price_List__c> priceList,String ontrigger){
       
    }     
}